project:
  type: website
execute:
  freeze: auto
website:
  title: "CodeBeast"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bhagesh-codebeast
      - icon: linkedin
        href: https://www.linkedin.com/in/bhagesh-hunakunti
format:
  html:
    title-block-banner-color: rgb(255, 255, 255)
    theme: 
      - zephyr
      - custom.scss
    css: styles.css



